"""Scam Detector Model and Service Unit Tests (Step d).

Covers:
- Model artifact loading (< 5 MB bundle)
- Score range 0-100 and signals extraction
- High risk score for electricity cut-off and bank KYC scams
- Low risk score for everyday family / temple texts
- Mandatory Safety Floor: OTP and UPI PIN requests are always >= 90
- Metrics file target validation (F1 >= 0.95)
- Alert family endpoint
"""

import json
from pathlib import Path
import pytest
from fastapi.testclient import TestClient

from backend.app.config import Settings, reset_settings_for_tests
from backend.app.main import create_app
from backend.app.ml.scam_detector import ScamDetector, get_scam_model


@pytest.fixture
def client():
    settings = Settings(ENVIRONMENT="dev", ALLOW_DEV_TOKENS=True, GEMINI_MOCK=True)
    reset_settings_for_tests(settings)
    app = create_app()
    return TestClient(app)


def test_model_loads_and_bundle_size():
    """Verify model loads into memory and is under 5 MB."""
    model = get_scam_model()
    assert model is not None

    bundle_path = Path(__file__).parent.parent / "app" / "ml" / "models" / "scam_model.joblib"
    assert bundle_path.exists()
    size_mb = bundle_path.stat().st_size / (1024 * 1024)
    assert size_mb < 5.0, f"Model artifact too large: {size_mb:.2f} MB"


def test_metrics_json_meets_f1_target():
    """Verify metrics.json exists and satisfies F1 >= 0.95 requirement."""
    metrics_path = Path(__file__).parent.parent.parent / "ml" / "metrics.json"
    assert metrics_path.exists(), "metrics.json was not generated by ml/evaluate.py"

    with open(metrics_path, "r", encoding="utf-8") as f:
        metrics = json.load(f)

    assert metrics["target_met"] is True
    sms_f1 = metrics["benchmark_sms_test"]["f1"]
    assert sms_f1 >= 0.95, f"SMS F1 is {sms_f1}, below the 0.95 threshold"


@pytest.mark.asyncio
async def test_known_scams_score_high():
    """Verify prevalent Indian fraud patterns score high (>= 75)."""
    electricity_scam = (
        "Dear consumer, your electricity power will be disconnected TONIGHT at 9:30 PM "
        "because your previous month bill was not updated. Please immediately contact our officer at 9876543210."
    )
    res1 = await ScamDetector.predict(electricity_scam)
    assert res1["risk_score"] >= 75
    assert res1["label"] == "scam"
    assert any("threat" in s.lower() or "बिजली" in s or "urgency" in s.lower() or "लहजा" in s for s in res1["top_signals"])

    bank_scam = (
        "State Bank of India: Your YONO netbanking has been suspended due to pending PAN card KYC. "
        "Click http://sbi-kyc-verify.cc to update immediately or account permanently blocked."
    )
    res2 = await ScamDetector.predict(bank_scam)
    assert res2["risk_score"] >= 75
    assert res2["label"] == "scam"


@pytest.mark.asyncio
async def test_known_safe_messages_score_low():
    """Verify normal everyday senior texts score low (<= 25)."""
    safe_family = "Hi Dad, I reached home safely. Will call you on video call in the evening."
    res1 = await ScamDetector.predict(safe_family)
    assert res1["risk_score"] <= 25
    assert res1["label"] == "safe"

    safe_temple = "नमस्ते शर्मा जी, कल सुबह मंदिर में सुंदरकांड का पाठ है। आप सपरिवार समय से पधारें।"
    res2 = await ScamDetector.predict(safe_temple)
    assert res2["risk_score"] <= 25
    assert res2["label"] == "safe"


@pytest.mark.asyncio
async def test_otp_upi_pin_safety_floor():
    """MANDATORY RULE: Any message asking for an OTP or UPI-PIN must score >= 90."""
    otp_msg = "Please share the 6 digit OTP you just received to verify your lottery prize."
    res1 = await ScamDetector.predict(otp_msg)
    assert res1["risk_score"] >= 90
    assert res1["label"] == "scam"

    pin_msg = "सर, आपके फोन पे पर 5000 का कैशबैक आया है। पाने के लिए अपना UPI पिन डालें।"
    res2 = await ScamDetector.predict(pin_msg)
    assert res2["risk_score"] >= 90
    assert res2["label"] == "scam"


def test_scam_api_check_and_alert_family(client):
    """Connected Workflow 2: Check suspicious message and alert family."""
    headers = {"Authorization": "Bearer dev-senior-sharma"}

    msg = "Urgent: Your electricity will be disconnected tonight. Call officer at 9811223344."
    check_res = client.post("/api/scam/check", headers=headers, json={"message_text": msg})
    assert check_res.status_code == 200
    check_data = check_res.json()
    assert check_data["risk_score"] >= 70
    assert "explanation" in check_data
    assert "signals" in check_data
    log_id = check_data["id"]

    # 1-Tap Alert Family
    alert_res = client.post("/api/scam/alert-family", headers=headers, json={"log_id": log_id})
    assert alert_res.status_code == 200
    alert_data = alert_res.json()
    assert alert_data["success"] is True
    assert "परिवार को" in alert_data["message"]
